################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
CMSIS/DSP_Lib/Source/FilteringFunctions/%.o CMSIS/DSP_Lib/Source/FilteringFunctions/%.su: ../CMSIS/DSP_Lib/Source/FilteringFunctions/%.c CMSIS/DSP_Lib/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DSTM32F769NIHx -DSTM32F769I_DISCO -DSTM32F7 -DSTM32 -DNO_DEBUG -DUSE_HAL_DRIVER -DSTM32F769xx -DINCLUDE_FATFS -DARM_MATH_CM7 -DUSE_USB_HS -D__FPU_PRESENT=1 -D__VFP_FP -DFPU_USED=1 -DNON_DIGI_FP -DSTM_SPDIF_OUT -DUSE_SD_CARD -DNON_USE_DMA2D -DUART_THREAD -c -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" @"CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c_includes.args"

clean: clean-CMSIS-2f-DSP_Lib-2f-Source-2f-FilteringFunctions

clean-CMSIS-2f-DSP_Lib-2f-Source-2f-FilteringFunctions:
	-$(RM) ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.o
	-$(RM) ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.o
	-$(RM) ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.su
	-$(RM) ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.su ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.d ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.o ./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-CMSIS-2f-DSP_Lib-2f-Source-2f-FilteringFunctions

